wad/hoteladmin/urls.py
from django.urls import path

app_name="hoteladmin"

wad/user/urls.py
from django.urls import path
from . import views
app_name='user'

urlpatterns = [
    path("",views.index,name="index"),
    path("login",views.view_login,name="login"),
    path("signup",views.signup,name="signup"),
    path("contact",views.contact,name="contact"),
    path("booking",views.booking,name="booking"),
    path("editbooking",views.editbooking,name="editbooking"),
    path("test",views.test,name="test")

]

wad/wad/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user',include("user.urls")),
    path('hoteladmin',include("hoteladmin.urls"))
    
]

wad/hoteladmin/models.py
from django.db import models

# Create your models here.

wad/hoteladmin/views.py
from django.shortcuts import render

# Create your views here.

wad/user/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.http  import HttpResponse
# Create your views here.


def index(request):
    return render(request,"user/index.html")

def signup(request):
    if(request.method=="POST"):
        #Error messages
        usernameexists="Username already exists.Choose a new username"
        userexists="Account already exists.Please sign in to continue"
        passerror="The passwords don't match.Please enter again"
        #POST data
        username=request.POST['username']
        password=request.POST.get('password')
        passverify=request.POST.get('password1')
        email=request.POST.get('email')

        #Checking whether the entered two passwords match
        if password != passverify:
            return render(request,"user/signup.html",{
                "message":passerror
            })
        
        #Checking if the username or the user already exists
        allusers=User.objects.all()
        for user in allusers:
            if(user.username==username):
                if(user.email==email):
                    return render(request,"user/signup.html",{
                        "message":userexists
                    })
                
                return render(request,"user/signup.html",{
                    "message":usernameexists
                })
        user=User.objects.create_user(username=username,password=password,email=email)
        user.save()
        userauth=authenticate(username=username,password=password)
        if userauth:
            return render(request,"user/login.html")
        else:
            return HttpResponse(request,"Cant create user")
    return render(request,"user/signup.html")
def view_login(request):
    if(request.method=="POST"):
        errormessage="Incorrect crendetials or the account doesnt exist"
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request,username=username,password=password)
        if user is not None:    
            login(request,user)
            return render(request,"user/index.html")
        else:
           return  render(request,"user/login.html",{
               "message":errormessage
           })
    return render(request,"user/login.html")
def contact(request):
    return render(request,"user/contact.html")

def booking(request):
    if request.method=="POST":
        date=request.POST["date"]
        return render(request,"user/test.html",{
            "date":date
        })
    return render(request,"user/booking.html")
def test(request):
    date=request.POST["date"]
    return render(request,"user/test.html",{
        "date":date
    })
def editbooking(request):
    pass

wad/user/templates/user/booking.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">

    <title>Reserve your table</title>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="../style.css">


</head>


<body>
    <div class="jumbotron ">
        <div class="container text-center bookTable ">
            <h1 class="upper-case">Book Your Table</h1>



        </div>
    </div>





    <form action="{% url 'user:test' %}" class="form-horizontal customerForm">
        {% csrf_token %}
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="user-name" class="col-lg-2 control-label">Name</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-user"></span>
                    <input type="text" class="form-control" name="name" id="user-name" placeholder="Enter you name" required>

                </div>

            </div>
        </div>
        <!-- End form group -->


        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="phone" class="col-lg-2 control-label">Contact</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-earphone"></span>
                    <input type="tel" class="form-control" name="phoneno" id="phone" placeholder="Phone Number" required>

                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-3 col-md-3"></div>
            <div class="form-group  col-md-6 col-lg-6 col-sm-12">
                <label for="party" class="col-lg-2 control-label">No of tables</label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <span class="input-group-addon glyphicon glyphicon-hand-right"></span>
                        <input type="tel" class="form-control" name="no" id="party" placeholder="Enter No of tables" required>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3"></div>
        </div>





        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="date" class="col-lg-2 control-label">Date</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-hand-right"></span>

                    <input type="date" class="form-control" id="date" name="date" placeholder="Choose a Date" required>
                </div>
            </div>
        </div>

        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="time" class="col-lg-2 control-label">Time</label>
            <div class="col-lg-10">

                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-hand-right"></span>
                    <input type="time" class="form-control" id="time" name="time" placeholder="Choose a Time" required>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-3 col-md-3"></div>
            <div class="form-group  col-md-6 col-lg-6 col-sm-12">
                <label for="user-message" class="col-lg-2 control-label">Message</label>
                <div class="col-lg-10">
                    <textarea name="user-message" id="user-message" name="message" class="form-control" cols="5" rows="10" placeholder="Enter your Special needs"></textarea>
                </div>
            </div>
            <div class="col-lg-3 col-md-3"></div>
        </div>




        <div class=" col-lg-12 form-group text-center">

            <input type="submit" value="Submit">

            <!--Modal to display the confirmation code-->

            <!--<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">-->
            <!--<div class="modal-dialog modal-sm">-->
            <!--<div class="modal-content" id="op"  >-->
            <!--...-->
            <!--</div>-->
            <!--</div>-->
            <!--</div>-->



            <!--<button type="button" id="edit" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Tooltip on right" data-content="Click to edit an existing reservation">Edit</button>-->

        </div>
        <hr>

    </form>



</body>

</html>

wad/user/templates/user/contact.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact</title>
    <link href="{% static 'user/contact.css' %}" type="text/css" rel="stylesheet" />
</head>

<body>
    <div class="cntfrm">
        <h1 id="hcn">Contact Us</h1>
        <p id="gr">Tablo beleive in good relationship with customer , so if you need any help feel free to contact us .</p>
        <div class="cnbox">
            <form>
                <input type="text" id="name" name="Name" placeholder="Name...">
                <input type="text" id="email" name="Email Id" placeholder="Email Id..">
                <textarea type="text" id="message" name="Message" placeholder="Message.."></textarea>
                <input type="submit" id="clk" value="Send Message">
            </form>
        </div>
    </div>
</body>

</html>

wad/user/templates/user/editbooking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit your Reservation</title>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"  crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">

    <link rel="stylesheet" href="style.css">



</head>
<body>

<div class="jumbotron ">
    <div class="container text-center bookTable ">
        <h1 class="upper-case">Edit Reservation</h1>
        <p>Enter the correct confirmation code to edit or cancel reservation</p>

    </div><!-- End container -->
</div>


<form action="" class="form-horizontal customerForm">

    <div class="row">
        <div class="col-lg-3 col-md-3"></div>
        <div class="form-group  col-md-6 col-lg-6 col-sm-12">
            <label for="party" class="col-lg-2 control-label">Conirmation Code</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon glyphicon-asterisk"></span>
                    <input type="tel" class="form-control" id="code" placeholder="code" required>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3"></div>
    </div>

    <div class="form-group col-md-6 col-lg-6 col-sm-12">
        <label for="user-name" class="col-lg-2 control-label">Name</label>
        <div class="col-lg-10">
            <div class="input-group">
                <span class="input-group-addon glyphicon glyphicon-user"></span>
                <input type="text" class="form-control" id="user-name" placeholder="Enter you name" required>

            </div>

        </div>
    </div><!-- End form group -->


    <div class="form-group col-md-6 col-lg-6 col-sm-12">
        <label for="phone" class="col-lg-2 control-label">Contact</label>
        <div class="col-lg-10">
            <div class="input-group">
                <span class="input-group-addon glyphicon glyphicon-earphone"></span>
                <input type="tel" class="form-control" pattern='[\+]\d{2}[\(]\d{2}[\)]\d{4}[\-]\d{4}' id="phone" placeholder="Phone Number" required>

            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-3 col-md-3"></div>
        <div class="form-group  col-md-6 col-lg-6 col-sm-12">
            <label for="party" class="col-lg-2 control-label">No of Tables</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-hand-right"></span>
                    <input type="tel" class="form-control" id="party" placeholder="Enter No of Tables" required>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3"></div>
    </div>





    <div class="form-group col-md-6 col-lg-6 col-sm-12">
        <label for="date" class="col-lg-2 control-label">Date</label>
        <div class="col-lg-10">
            <div class="input-group">
                <span class="input-group-addon glyphicon glyphicon-hand-right"></span>

                <input type="date" class="form-control" id="date" placeholder="Choose a Date" required>
            </div>
        </div>
    </div>

    <div class="form-group col-md-6 col-lg-6 col-sm-12">
        <label for="time" class="col-lg-2 control-label">Time</label>
        <div class="col-lg-10">

            <div class="input-group">
                <span class="input-group-addon glyphicon glyphicon-hand-right"></span>
                <input type="time" class="form-control" id="time" placeholder="Choose a Time" required>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-3 col-md-3"></div>
        <div class="form-group  col-md-6 col-lg-6 col-sm-12">
            <label for="user-message" class="col-lg-2 control-label">Message</label>
            <div class="col-lg-10">
                    <textarea name="user-message" id="user-message" class="form-control"
                              cols="5" rows="10" placeholder="Enter your Special needs"></textarea>
            </div>
        </div>
        <div class="col-lg-3 col-md-3"></div>
    </div>




    <div class=" col-lg-12 form-group text-center" >


        <!--<button type="button" id="edit" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Tooltip on right" data-content="Click to edit an existing reservation">Edit</button>-->
        <a href="editbooking.html" class="btn btn-warning ">Confirm</a>
        <a href="#" class="btn btn-warning ">Cancel</a>
    </div>
    <hr>

</form>


</body>
</html>

wad/user/templates/user/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'user/index.css' %}" type="text/css" rel="stylesheet" />

</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a class="o1" href="{% url 'user:login' %}">Login</a>
        <a class="o2" href="{% url 'user:signup' %}">Signup</a>
        <a class="o3" href="{% url 'user:contact' %}">Contact Us</a>
        <a class="o4" href="#scan"><img id="scamg" src="https://img.icons8.com/ios/2x/qr-code--v2.gif" alt=""></a>
        <img src="https://media.istockphoto.com/vectors/people-set-profession-waiter-vector-id954891426?k=6&m=954891426&s=612x612&w=0&h=WpjbuIUXPGQsZCC2-tGpf0r1ZgNhZTJdCi3Ot1T-p6c=" alt="" id="navimg">
    </div>

    <div class="row1" id="main">
        <span id="sp1" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
        <div class="cola one">
            <div class="box1" id="main1">
                <img id="img1" src="https://media3.giphy.com/media/l1NbTlEHomLoTEoZBP/giphy.gif">
            </div>
        </div>
        <div class="cola two">
            <div class="box2">
                <div class="options" id="opt">
                    <a class="o1" href="{% url 'user:login' %}">Login</a>
                    <a class="o2" href="{% url 'user:signup' %}">Signup</a>
                    <a class="o3" href="#cnbox">Contact Us</a>
                    <a class="o4" href="{% url 'user:booking' %}"><img id="scamg" src="https://img.icons8.com/ios/2x/qr-code--v2.gif" alt=""></a>
                </div>

                <img id="logo" src="{% static 'user/tablologo.png' %}">
                <h1 id="mainheading">TablO</h1>
                <input type="text" id="search" onkeyup="" placeholder="Search.." title="Type in a category">
            </div>
        </div>
    </div>

    <div class="stepbox">
        <div class="stepsa">
            <img class="b1 scan" src="https://media1.giphy.com/media/KjWDaVqI6waTtJmEXT/giphy.webp?cid=ecf05e47i401b8q0fz8rt4brgop90rx50sm3oni5tg19h0xb&rid=giphy.webp" alt="">
            <h1 class="b1 step1">Scan QR CODE</h1>
        </div>
        <div class="stepsb">
            <h1 class="b3 step2">ORDER</h1>
            <img class="b3 scan2" src="https://media4.giphy.com/media/26BRJtpO9vE6LJCWk/200w.webp?cid=ecf05e47wth8zbzqqk2y9h27tmy670m5xzmm4fd0hifv4y5y&rid=200w.webp" alt="">
        </div>
    </div>
    <div class="info">

        <div class="info1 inftxt1"><img id="infimg" src="https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375__340.png" alt=""></div>
        <div class="info1 inftxt2">
            <p>Don't waste food .</p>
            <p>Take as much you can eat .</p>
        </div>

    </div>
    <div class="rowp">
        <div class="colp colq">
            <img class="dish1" src="https://images.unsplash.com/photo-1596450512748-2dae774fc38a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTl8fGluZGlhbiUyMGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" " alt=" ">
		     <div class="dishname1 ">
				 <a id="flink " href=" "><h1>INDIAN FOOD</h1></a>
			 </div>
		</div>
		<div class="colp colr ">
			<img class="dish1 "  src="https://images.unsplash.com/photo-1512152272829-e3139592d56f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8ZmFzdCUyMGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 ">
            <div class="dishname1 ">
				<a id="flink " href=" "><h1>BURGER</h1></a>
			</div>
		</div>
		<div class="colp cols ">
            <img class="dish1 " src="https://images.unsplash.com/photo-1513104890138-7c749659a591?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emF8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 ">
			<div class="dishname1 ">
				<a id="flink " href=" "><h1>PIZZA</h1></a>
			</div>
		</div>
	</div>
	<div class="rowp ">
		<div class="colp colq ">
			<img class="dish1 " src="https://images.unsplash.com/photo-1504712168631-d59c8516c409?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzV8fGljZWNyZWFtfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 ">
            <div class="dishname1 ">
				<a id="flink " href=" "><h1>ICE CREAM</h1></a>
			</div>
		</div>
		<div class="colp colr ">
			<img class="dish1 " src="https://images.unsplash.com/photo-1500353391678-d7b57979d6d2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzJ8fGNvZmZlZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 "> 
         <div class="dishname1 ">
            <a id="flink " href=" "><h1>COFFEE</h1></a>
			</div>
		</div>
		<div class="colp cols ">
			<img class="dish1 " src="https://images.unsplash.com/photo-1518047601542-79f18c655718?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTZ8fGNha2V8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 " >
            <div class="dishname1 ">
				<a id="flink " href=" "><h1>CAKE</h1></a>
			</div>
		</div> 
	</div>
    <hr>
	<div class="cntfrm ">
        <h1 id="hcn ">Contact Us</h1>
        <p id="gr ">Tablo beleive in good relationship with customer , so if you need any help feel free to contact us .</p>
        <div class="cnbox "id="cnbox ">
            <form>
               <input type="text " id="name " name="Name " placeholder="Name... ">
               <input type="text " id="email " name="Email Id " placeholder="Email Id.. ">
	           <textarea type="text " id="message " name="Message " placeholder="Message.. "></textarea>
               <input type="submit " id="clk " value="Send Message ">
            </form>
          </div>
    </div>
    
    <div class="foot ">
        <div class="f f1 ">
             <h1>About us</h1>
             <p>
                 Tablo is made to serve people . It help people to order food sitting in restaurant without any contact. You need to just scan qr code and select from menu and order .
             </p>
             <p>
                 ENJOY YOUR MEAL 
             </p>
        </div>
        <hr>
        <div class="f f3 ">
            <h1>SOCIAL MEDIA</h1>
            <a href=" "><img id="footimg " src="https://img.icons8.com/fluent/2x/instagram-new.png " alt=" "></a>
            <a href=" "><img id="footimg " src="https://img.icons8.com/fluent/2x/facebook-new.png " alt=" "></a>
            <a href=" "><img id="footimg " src="https://img.icons8.com/color/2x/youtube-play.png " alt=" "></a>
            <a href=" "><img id="footimg " src="https://img.icons8.com/fluent/2x/twitter.png " alt=" "></a>
        </div>
    </div>

    <script>
        function openNav() {
          document.getElementById("mySidenav ").style.width = "250px ";
          document.getElementById("main ").style.marginLeft = "0px ";
          document.body.style.backgroundColor = "rgba(0,0,0,0.4) ";
        }
        
        function closeNav() {
          document.getElementById("mySidenav ").style.width = "0 ";
          document.getElementById("main ").style.marginLeft= "0 ";
          document.body.style.backgroundColor = "white ";
        }
        </script>
</body>
</html>

wad/user/templates/user/login.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="{% static 'user/login.css'%}" type="text/css" rel="stylesheet" />
</head>

<body>
    <div class="signbox">
        <h1 style="text-align: center;color: white;">WELCOME BACK</h1>
        <h1 style="text-align: center;color: white;">Login</h1>
        <form action={% url 'user:login' %} method="post">
            {% csrf_token %} {%if message%}
            <hr>
            <p style="color: red">{{message}}</p>
            <hr> {%endif%}
            <label for="lname" id="lbl">User Name</label>
            <input type="text" id="username" name="username" placeholder="User Name">

            <label for="country" id="lbl">Password</label>
            <input type="password" id="password" name="password" placeholder="Password..">


            <input type="submit" value="Login">
        </form>
    </div>
</body>

</html>

wad/user/templates/user/signup.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'user/signup.css' %}" type="text/css" rel="stylesheet" />
</head>

<body>

    <div class="signbox">
        <h1 style="text-align: center;color: white;">WELCOME TO TABLO</h1>
        <h1 style="text-align: center;color: white;">Signup</h1>
        <form action={% url 'user:signup' %} method="post">
            {% csrf_token %}
            <label for="username" id="lbl">User Name</label> {%if message%}
            <hr>
            <p style="color: red">{{message}}</p>
            <hr> {%endif%}
            <input type="text" id="username" name="username" placeholder="User Name..">

            <label for="email" id="lbl">Email Id</label>
            <input type="email" id="email" name="email" placeholder="abcd@gmail.com">

            <label for="password" id="lbl">Password</label>
            <input type="password" id="password" name="password" placeholder="Password..">

            <label for="" id="lbl">Re-Enter Password</label>
            <input type="password" id="password1" name="password1" placeholder="Re-Enter Password">

            <input type="submit" value="Submit">
        </form>
    </div>


</body>

</html>

wad/user/templates/user/test.html
<!DOCTYPE html>

<html>

<head>
    <title>The Index Page</title>
</head>

<body>

</body>

</html>